### ISSUE TITLE
Color titles by category

### ISSUE THREAD

**Issue by smythp** [smythp/NEH-impact#2]
Research Programs
Preservation and Access
Education Programs
Public Programs
Digital Humanities
Federal/State Partnership
Challenge Grants
Agency-wide Projects

**Comment by story645** [comment]
Sorry! That was only from the 2010s. Here's the full list


Research Programs - 27,331
Public Programs - 10,485
Education Programs - 10,041
Preservation and Access - 5,965
Fellowships and Seminars - 5,452
Federal/State Partnership - 1,878
Challenge Grants - 1,727
Digital Humanities - 464
Miscellaneous Humanities Projects - 382
Research/Education - 5
Agency-wide Projects - 4
